before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    hooks:
      post:
        - upx --brute '{{ .Env.PWD }}/dist/{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}/qbconf'
    ldflags: -s -w -X main.version={{.Version}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64    
    binary: qbconf    
    targets:
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64
      - darwin_amd64
      - darwin_arm64    

archives:
  - id: qbconf
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  -
    name: qbconf
    homepage: "https://github.com/RaftechNL/qbconf"
    tap:
      owner: RaftechNL
      name: homebrew-toolbox
