before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    hooks:
      post:
        - upx --brute '{{ .Env.PWD }}/dist/{{ .Os }}_{{ .Arch }}_qbconf'
    ldflags: -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64    
    no_unique_dist_dir: true
    binary: '{{ .Os }}_{{ .Arch }}_qbconf'

archives:
  - id: qbconf
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  -
    name: qbconf
    homepage: "https://github.com/RaftechNL/qbconf"
    tap:
      owner: RaftechNL
      name: homebrew-toolbox
    install: |
      bin.install "qbconf"